---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aged-api-deployment
  labels:
    app: aged-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aged-api
  template:
    metadata:
      labels:
        app: aged-api
    spec:
      containers:
        - name: aged-api
          imagePullPolicy: Always
          image: jbolivar101/app-api:0.1
          env:
          - name: REDIS_IP
            value: 172.17.0.4        #UNSURE 
          ports:
          - name: http
            containerPort: 5000
