---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aged-db-deployment
  labels:
    app: aged-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aged-db
  template:
    metadata:
      labels:
        app: aged-db
    spec:
      containers:
        - name: aged-db
          image: redis:6
          ports:
          - name: http
            containerPort: 6379
            ports:
          volumeMounts:
            - name: read
              mountPath: "/read"
      volumes:
      - name: read
        persistentVolumeClaim:
          claimName: read
