---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: read
  labels:
    app: aged-redis  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
