FROM python:3.9

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY owid-energy-data.csv /app/
COPY ./src/* /app/

WORKDIR /app
ENTRYPOINT ["python"]
CMD ["app.py"]
